CREATE TABLE ADMIN 
(
  ADMIN_ID VARCHAR2(20 BYTE) NOT NULL 
, ADMIN_NAME VARCHAR2(20 BYTE) NOT NULL 
, ADMIN_PASSWORD VARCHAR2(16 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

COMMENT ON COLUMN ADMIN.ADMIN_ID IS '관리자의 ID';

COMMENT ON COLUMN ADMIN.ADMIN_NAME IS '관리자의 이름';

COMMENT ON COLUMN ADMIN.ADMIN_PASSWORD IS '관리자의 비밀번호';
