CREATE TABLE BASKET 
(
  CUST_ID VARCHAR2(30 BYTE) 
, PRO_NAME VARCHAR2(50 BYTE) 
, PRO_PRICE NUMBER 
, PRO_DISCOUNT_PRICE NUMBER 
, BUY_DATE DATE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;
