CREATE TABLE CUSTOMER 
(
  CUST_ID VARCHAR2(20 BYTE) NOT NULL 
, CUST_NAME VARCHAR2(20 BYTE) NOT NULL 
, CUST_PASSWORD VARCHAR2(16 BYTE) NOT NULL 
, CUST_TEL NUMBER(11, 0) NOT NULL 
, CUST_EMAIL VARCHAR2(30 BYTE) NOT NULL 
, CUST_ADDRESS VARCHAR2(100 BYTE) NOT NULL 
, CUST_GRADE VARCHAR2(20 BYTE) DEFAULT 'ªıΩœ»∏ø¯' NOT NULL 
, CUST_DATE DATE 
, CONSTRAINT CUSTOMER_PK PRIMARY KEY 
  (
    CUST_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CUSTOMER_PK ON CUSTOMER (CUST_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

COMMENT ON COLUMN CUSTOMER.CUST_ID IS '∞Ì∞¥¿« ID';

COMMENT ON COLUMN CUSTOMER.CUST_NAME IS '∞Ì∞¥¿« ¿Ã∏ß';

COMMENT ON COLUMN CUSTOMER.CUST_PASSWORD IS '∞Ì∞¥¿« PW';

COMMENT ON COLUMN CUSTOMER.CUST_TEL IS '∞Ì∞¥¿« ø¨∂Ù√≥';

COMMENT ON COLUMN CUSTOMER.CUST_EMAIL IS '∞Ì∞¥¿« ¿Ã∏ﬁ¿œ';

COMMENT ON COLUMN CUSTOMER.CUST_ADDRESS IS '∞Ì∞¥¿« ¡÷º“';

COMMENT ON COLUMN CUSTOMER.CUST_GRADE IS '∞Ì∞¥¿« µÓ±ﬁ';

COMMENT ON COLUMN CUSTOMER.CUST_DATE IS '∞Ì∞¥¿« ∞°¿‘¿œ';
